import * as utils from "./common.mjs";
import {NS_HTML} from "./common.mjs";
import {DocumentCloner} from "./doc-cloner.mjs";

/**
 * Base document rewriter with common features.
 */
class BaseDocumentRewriter {
  static run(...args) {
    const rewriter = new this();
    const result = rewriter.run(...args);
    if (utils.isPromise(result)) {
      return result.then(() => rewriter);
    }
    return rewriter;
  }

  run(doc) {
    this.doc = doc;
    this.processRootNode(doc);
  }

  processRootNode(rootNode) {
    throw new Error('Not implemented');
  }

  debug(...args) {
    console.debug(...args);
  }

  log(...args) {
    console.log(...args);
  }

  warn(...args) {
    console.warn(...args);
  }

  error(...args) {
    console.error(...args);
  }
}

/**
 * Add cloned document support.
 */
const MapperMixin = (base) => class extends base {
  /**
   * Clone the input document and run with a new instance.
   */
  static runWithClone(doc, {includeShadowDom, ...options} = {}) {
    const {newDoc, origNodeMap, clonedNodeMap} = this.clone(doc, {includeShadowDom});
    return super.run(newDoc, {...options, origNodeMap, clonedNodeMap});
  }

  /**
   * Set up mappings and clone a document.
   */
  static clone(doc, {includeShadowDom} = {}) {
    const origNodeMap = new WeakMap();
    const clonedNodeMap = new WeakMap();
    const newDoc = DocumentCloner.clone(doc, {origNodeMap, clonedNodeMap, includeShadowDom});
    return {newDoc, origNodeMap, clonedNodeMap};
  }

  /**
   * @return {Document} The original document when mapped, or the input
   *   document itself otherwise.
   */
  get origDoc() {
    const value = this.origNodeMap?.get(this.doc) || this.doc;
    Object.defineProperty(this, "origDoc", {value});
    return value;
  }

  /**
   * Should pass the cloned document for rewriting, with origNodeMap and
   * clonedNodeMap to access the corresponding nodes in the original document.
   *
   * @param {Document} doc - the document for rewriting.
   * @param {Object} [options]
   * @param {Map|WeakMap} [options.origNodeMap]
   * @param {Map|WeakMap} [options.clonedNodeMap]
   */
  run(doc, {origNodeMap, clonedNodeMap} = {}) {
    Object.assign(this, {doc, origNodeMap, clonedNodeMap});
    this.processRootNode(doc);
  }

  getOrigNode(node) {
    return this.origNodeMap?.get(node);
  }

  getClonedNode(node) {
    return this.clonedNodeMap?.get(node);
  }
};

class DocumentRewriter extends BaseDocumentRewriter {
  static get _singleton() {
    if (this.hasOwnProperty('_singleton_value')) {
      return this._singleton_value;
    }
    return this._singleton_value = new this();
  }

  static eraseRange(...args) {
    return this._singleton.eraseRange(...args);
  }

  static eraseNode(...args) {
    return this._singleton.eraseNode(...args);
  }

  static uneraseNode(...args) {
    return this._singleton.uneraseNode(...args);
  }

  /**
   * Add a recording attribute to mark the element as added, if requested.
   *
   * @param {Element} elem - The element to handle.
   * @param {Object} [context]
   *
   * @TODO: remove recording attributes with same timeId.
   */
  captureRecordAddedNode(elem, {
    record = false,
    timeId,
  } = {}) {
    if (record) {
      const recordAttr = `data-scrapbook-orig-null-node-${timeId}`;
      if (!elem.hasAttribute(recordAttr)) {
        elem.setAttribute(recordAttr, '');
      }
    }
  }

  /**
   * Remove the specified node. Add a recording attribute if requested.
   *
   * @param {Element} elem - The element to remove.
   * @param {Object} [context]
   *
   * @TODO: restore recording attributes with same timeId before generating the
   * comment.
   * @TODO: also support non-Element node types?
   */
  captureRemoveNode(elem, {
    record = false,
    timeId,
  } = {}) {
    if (!elem.parentNode) { return; }

    if (record) {
      const comment = elem.ownerDocument.createComment(`scrapbook-orig-node-${timeId}=${utils.escapeHtmlComment(elem.outerHTML)}`);
      elem.parentNode.replaceChild(comment, elem);
    } else {
      elem.parentNode.removeChild(elem);
    }
  }

  /**
   * Rewrite the specified attribute. Add a recording attribute if requested.
   *
   * When `ns` is specified, the prefix of the manipulated attribute will be
   * automatically looked up from the specified `ns`.  If the lookup result is
   * null, the prefix of `attr` will be taken.  If `attr` is not prefixed, a
   * unique prefix and `xmlns:*` will be automatically generated by the browser
   * when serializing with an API like `outerHTML`.
   *
   * For an HTML document, which is namespace agnostic, an appropriate prefix
   * will be selected when serializing with an API like `outerHTML` for certain
   * supported foreign namespaces (e.g., `attr` or `x:attr` becomes
   * `xlink:attr` when the attribute is in XLINK (http://www.w3.org/1999/xlink)
   * namespace), while no `xmlns:*` will be generated.
   * Otherwise, the prefix is kept as-is, but the attribute will become null
   * namespace when read from the serialized string.
   *
   * @param {Element} elem - The element to handle.
   * @param {string} [attr] - The attribute name to handle.
   *   - It's not allowed to contain more than one ":".
   *   - It's not allowed to contain a ":" prefix if `ns` is null.
   *   - In general an unprefixed name is preferred.
   * @param {?(string|boolean)} [value] - The value to assign.
   *   - If value is true, attr will be set to "" iff not exist.
   *   - If value is false/null/undefined, attr will be removed.
   * @param {Object} [context]
   * @param {?string} [context.ns] - The namespace for the attribute.
   */
  captureRewriteAttr(elem, attr, value, {
    ns = null,
    record = false,
    timeId,
  } = {}) {
    const [defaultPrefix, local] = utils.splitXmlAttribute(attr);
    let prefix = elem.lookupPrefix(ns) ?? defaultPrefix;
    prefix = prefix ? prefix + ":" : "";
    attr = `${prefix}${local}`;

    if (elem.hasAttributeNS(ns, local)) {
      if (value === true) { return; }

      const oldValue = elem.getAttributeNS(ns, local);
      if (oldValue === value) { return; }

      if ([false, null, undefined].includes(value)) {
        elem.removeAttributeNS(ns, local);
      } else {
        elem.setAttributeNS(ns, attr, value);
      }

      if (record) {
        const recordAttr = `data-scrapbook-orig-attr-${local}-${timeId}`;
        const recordAttr2 = `data-scrapbook-orig-null-attr-${local}-${timeId}`;
        const recordAttr3 = `data-scrapbook-orig-null-node-${timeId}`;
        if (!elem.hasAttributeNS(ns, recordAttr) && !elem.hasAttributeNS(ns, recordAttr2) && !elem.hasAttribute(recordAttr3)) {
          elem.setAttributeNS(ns, `${prefix}${recordAttr}`, oldValue);
        }
      }
    } else {
      if ([false, null, undefined].includes(value)) { return; }

      if (value === true) { value = ''; }

      elem.setAttributeNS(ns, attr, value);

      if (record) {
        const recordAttr = `data-scrapbook-orig-null-attr-${local}-${timeId}`;
        const recordAttr2 = `data-scrapbook-orig-attr-${local}-${timeId}`;
        const recordAttr3 = `data-scrapbook-orig-null-node-${timeId}`;
        if (!elem.hasAttributeNS(ns, recordAttr) && !elem.hasAttributeNS(ns, recordAttr2) && !elem.hasAttribute(recordAttr3)) {
          elem.setAttributeNS(ns, `${prefix}${recordAttr}`, "");
        }
      }
    }
  }

  /**
   * Rewrite the textContent. Add a recording attribute if requested.
   *
   * @param {Element} elem - The element to handle.
   * @param {string} value - The text content value to assign.
   * @param {Object} [context]
   */
  captureRewriteTextContent(elem, value, {
    record = false,
    timeId,
  } = {}) {
    const oldValue = elem.textContent;
    if (oldValue === value) { return; }

    elem.textContent = value;

    if (record) {
      const recordAttr = `data-scrapbook-orig-textcontent-${timeId}`;
      if (!elem.hasAttribute(recordAttr)) { elem.setAttribute(recordAttr, oldValue); }
    }
  }

  /**
   * Replace nodes in the range with a serialized HTML comment.
   */
  eraseRange(range, {
    timeId = utils.dateToId(),
    mapWrapperToComment,
    mapCommentToWrapper,
  } = {}) {
    const doc = range.commonAncestorContainer.ownerDocument;
    const wrapper = doc.createElement('scrapbook-erased');
    range.surroundContents(wrapper);
    this.htmlify(wrapper);
    const comment = doc.createComment(`scrapbook-erased${timeId ? '-' + timeId : ''}=${utils.escapeHtmlComment(wrapper.innerHTML)}`);
    mapWrapperToComment?.set(wrapper, comment);
    mapCommentToWrapper?.set(comment, wrapper);
    wrapper.replaceWith(comment);
  }

  /**
   * Replace node with a serialized HTML comment.
   */
  eraseNode(node, options) {
    const range = node.ownerDocument.createRange();
    range.selectNode(node);
    return this.eraseRange(range, options);
  }

  /**
   * Replace a serialized HTML comment with the original nodes.
   *
   * @return {boolean} Whether the unerase is successful.
   */
  uneraseNode(node, {
    mapCommentToWrapper,
    normalize = true,
  } = {}) {
    const parent = node.parentNode;
    if (!parent) { return false; }

    // if the associated source nodes exist, use them
    const wrapper = mapCommentToWrapper?.get(node);
    if (wrapper) {
      const frag = node.ownerDocument.createDocumentFragment();
      let child;
      while (child = wrapper.firstChild) {
        frag.appendChild(child);
      }
      this.unhtmlify(frag, {apply: false});
      node.replaceWith(frag);
      if (normalize) {
        parent.normalize();
      }
      return true;
    }

    // otherwise, recover from recorded HTML
    const m = node.nodeValue.match(/^.+?=([\s\S]*)$/);
    if (m) {
      const doc = node.ownerDocument;
      const t = doc.createElement('template');
      t.innerHTML = utils.unescapeHtmlComment(m[1]);
      const frag = doc.importNode(t.content, true);
      this.unhtmlify(frag);
      node.replaceWith(frag);
      if (normalize) {
        parent.normalize();
      }
      return true;
    }

    return false;
  }

  /**
   * Remove scrapbook toolbar related elements and attributes.
   */
  removeToolbar(rootNode) {
    this.captureRewriteAttr(rootNode, 'data-scrapbook-toolbar-active', null, {record: false});
    for (const elem of rootNode.querySelectorAll('[data-scrapbook-elem|="toolbar"]')) {
      elem.remove();
    }
  }

  /**
   * Convert dynamic information into representable HTML attributes recursively.
   *
   * @param {Element|Document|ShadowRoot} node
   * @param {Object} [options]
   * @param {Map} [options.adoptedStyleSheetMap] - shared map for constructed
   *   stylesheets.
   *
   * @TODO: use shared constructed stylesheets among shadow roots
   */
  htmlify(node, options = {}) {
    this._htmlify_tree(node, options);
  }

  _htmlify_tree(node, options = {}) {
    // handle adoptedStyleSheet if supported by the browser
    if (node.adoptedStyleSheets && (node.host || node.nodeType === Node.DOCUMENT_NODE)) {
      const {adoptedStyleSheetMap = new Map()} = options;
      this._htmlify_adoptedStyleSheets(node, {adoptedStyleSheetMap});
      if (!options.adoptedStyleSheetMap) {
        const elem = node.host ?? node.documentElement;
        this._htmlify_sharedAdoptedStyleSheets(elem, {adoptedStyleSheetMap});
      }
    }

    // handle manual slots
    if (node.host && node.slotAssignment === 'manual') {
      this._htmlify_slots(node);
    }

    this._htmlify(node, options);
    for (const elem of node.querySelectorAll('*')) {
      this._htmlify(elem, options);
    }
  }

  _htmlify(elem, options = {}) {
    if (elem.nodeType !== Node.ELEMENT_NODE) { return; }

    this[`_htmlify_{${elem.namespaceURI}}${elem.localName}`]?.(elem, options);

    this._htmlify_shadowHost(elem, (shadowRoot) => {
      this._htmlify_tree(shadowRoot, options);
    });
  }

  /**
   * Record serialized shadow DOM information.
   *
   * @param {Element} elem - The shadow host element.
   * @param {Function} [callback] - The callback to rewrite the shadow root.
   */
  _htmlify_shadowHost(elem, callback) {
    this._unhtmlify_shadowHost_attrs(elem);

    const shadowRoot = utils.getShadowRoot(elem);
    if (!shadowRoot) { return false; }

    callback?.call(this, shadowRoot);

    this.captureRewriteAttr(elem, "data-scrapbook-shadowdom", shadowRoot.innerHTML, {record: false});
    if (shadowRoot.mode !== 'open') {
      this.captureRewriteAttr(elem, "data-scrapbook-shadowdom-mode", shadowRoot.mode, {record: false});
    }
    if (shadowRoot.clonable) {
      this.captureRewriteAttr(elem, "data-scrapbook-shadowdom-clonable", true, {record: false});
    }
    if (shadowRoot.delegatesFocus) {
      this.captureRewriteAttr(elem, "data-scrapbook-shadowdom-delegates-focus", true, {record: false});
    }
    if (shadowRoot.serializable) {
      this.captureRewriteAttr(elem, "data-scrapbook-shadowdom-serializable", true, {record: false});
    }
    if (shadowRoot.slotAssignment && shadowRoot.slotAssignment !== 'named') {
      this.captureRewriteAttr(elem, "data-scrapbook-shadowdom-slot-assignment", shadowRoot.slotAssignment, {record: false});
    }

    return true;
  }

  /**
   * Collect and record used constructed stylesheets.
   *
   * @param {Document|ShadowRoot} rootNode
   * @param {Object} options
   * @param {Map} options.adoptedStyleSheetMap
   * @param {Function} [options.cssRewriter]
   */
  _htmlify_adoptedStyleSheets(rootNode, {adoptedStyleSheetMap, cssRewriter}) {
    this._unhtmlify_adoptedStyleSheets(rootNode, {apply: false});

    const rootNodeOrig = this.getOrigNode ? this.getOrigNode(rootNode) : rootNode;
    if (!rootNodeOrig) { return; }

    const infos = [];
    for (const css of utils.getAdoptedStyleSheets(rootNodeOrig)) {
      let info = adoptedStyleSheetMap.get(css);
      if (info) {
        info.roots.push(rootNode);
      } else {
        info = {
          id: adoptedStyleSheetMap.size,
          roots: [rootNode],
        };
        adoptedStyleSheetMap.set(css, info);
      }
      infos.push(info);
      cssRewriter?.call(this, css, rootNode);
    }
    if (infos.length) {
      const elem = rootNode.host ?? rootNode.documentElement;
      this.captureRewriteAttr(elem, "data-scrapbook-adoptedstylesheets", infos.map(x => x.id).join(','), {record: false});
    }
  }

  /**
   * Record collected constructed stylesheets.
   *
   * @param {Element} elem - The documentElement or shadow host to record.
   * @param {Object} options
   * @param {Map} options.adoptedStyleSheetMap
   * @param {Function} [options.rewriter]
   */
  _htmlify_sharedAdoptedStyleSheets(elem, {
    adoptedStyleSheetMap,
    rewriter = (elem, id, css, roots) => {
      const cssText = Array.prototype.map.call(css.cssRules, r => r.cssText).join('\n\n');
      this.captureRewriteAttr(elem, `data-scrapbook-adoptedstylesheet-${id}`, cssText, {record: false});
    },
  }) {
    this._unhtmlify_sharedAdoptedStyleSheets(elem, {apply: false});

    if (!adoptedStyleSheetMap.size) { return false; }
    for (const [css, {id, roots}] of adoptedStyleSheetMap) {
      rewriter?.call(this, elem, id, css, roots);
    }
    return true;
  }

  /**
   * Update records for all slots and slottables of a shadow root.
   *
   * @param {ShadowRoot} rootNode
   * @param {Object} [options]
   * @param {Map} [options.slotMap]
   */
  _htmlify_slots(rootNode, {slotMap = new Map()} = {}) {
    this._unhtmlify_slots(rootNode, {apply: false});

    for (const elem of rootNode.querySelectorAll("slot")) {
      if (elem.namespaceURI !== NS_HTML) { continue; }

      const elemOrig = this.getOrigNode ? this.getOrigNode(elem) : elem;
      if (!elemOrig) { continue; }

      const ids = [];
      for (const targetNodeOrig of elemOrig.assignedNodes()) {
        const targetNode = this.getClonedNode ? this.getClonedNode(targetNodeOrig) : targetNodeOrig;
        let id = slotMap.get(targetNode);
        if (typeof id === 'undefined') {
          id = slotMap.size;
          slotMap.set(targetNode, id);
        }
        if (targetNode.nodeType === Node.ELEMENT_NODE) {
          this.captureRewriteAttr(targetNode, "data-scrapbook-slot-index", id, {record: false});
        } else {
          const doc = targetNode.ownerDocument;
          targetNode.before(doc.createComment(`scrapbook-slot-index=${id}`));
          targetNode.after(doc.createComment(`/scrapbook-slot-index`));
        }
        ids.push(id);
      }
      if (ids.length) {
        this.captureRewriteAttr(elem, "data-scrapbook-slot-assigned", ids.join(','), {record: false});
      }
    }
  }

  [`_htmlify_{${NS_HTML}}canvas`](elem) {
    this[`_unhtmlify_{${NS_HTML}}canvas`](elem, {apply: false});

    const elemOrig = this.getOrigNode ? this.getOrigNode(elem) : elem;
    if (!elemOrig) { return; }

    let data;
    try {
      data = elemOrig.toDataURL();
    } catch (ex) {
      console.error(ex);
    }

    if (data && data !== utils.getBlankCanvasData(elemOrig)) {
      this.captureRewriteAttr(elem, "data-scrapbook-canvas", data, {record: false});
      return true;
    }

    return false;
  }

  [`_htmlify_{${NS_HTML}}input`](elem, {mode = "save"} = {}) {
    switch (elem.type?.toLowerCase()) {
      case undefined:
      case "image":
      case "file": {
        return false;
      }
      case "radio":
      case "checkbox": {
        return this[`_htmlify_{${NS_HTML}}input#radio`](elem, {mode});
      }
      case "password": {
        return this[`_htmlify_{${NS_HTML}}input#password`](elem, {mode});
      }
      default: {
        return this[`_htmlify_{${NS_HTML}}input#text`](elem, {mode});
      }
    }
  }

  [`_htmlify_{${NS_HTML}}input#radio`](elem, {mode = "save"} = {}) {
    this[`_unhtmlify_{${NS_HTML}}input#radio`](elem, {apply: false});

    let result = false;
    const elemOrig = this.getOrigNode ? this.getOrigNode(elem) : elem;
    if (!elemOrig) { return result; }

    const isCheckbox = elem.type?.toLowerCase() === 'checkbox';
    switch (mode) {
      case "save-all":
      case "save": {
        const checked = elemOrig.checked;
        if (checked !== elem.hasAttribute('checked')) {
          this.captureRewriteAttr(elem, "data-scrapbook-input-checked", String(checked), {record: false});
          result = true;
        }
        if (isCheckbox && elemOrig.indeterminate) {
          this.captureRewriteAttr(elem, "data-scrapbook-input-indeterminate", true, {record: false});
          result = true;
        }
        break;
      }
      case "keep-all":
      case "keep": {
        if (isCheckbox && elemOrig.indeterminate) {
          this.captureRewriteAttr(elem, "data-scrapbook-input-indeterminate", true, {record: false});
          result = true;
        }
      }
      // eslint-disable-next-line no-fallthrough
      case "html-all":
      case "html": {
        this.captureRewriteAttr(elem, "checked", elemOrig.checked);
        break;
      }
      case "reset":
      default: {
        // do nothing
        break;
      }
    }

    return result;
  }

  [`_htmlify_{${NS_HTML}}input#password`](elem, {mode = "save"} = {}) {
    this[`_unhtmlify_{${NS_HTML}}input#text`](elem, {apply: false});

    let result = false;
    const elemOrig = this.getOrigNode ? this.getOrigNode(elem) : elem;
    if (!elemOrig) { return result; }

    switch (mode) {
      case "save-all": {
        const value = elemOrig.value;
        if (value !== (elem.getAttribute('value') ?? '')) {
          this.captureRewriteAttr(elem, "data-scrapbook-input-value", value, {record: false});
          result = true;
        }
        break;
      }
      case "keep-all":
      case "html-all": {
        const value = elemOrig.value;
        if (value !== (elem.getAttribute('value') ?? '')) {
          this.captureRewriteAttr(elem, "value", value);
        }
        break;
      }
      case "save":
      case "keep":
      case "html":
      case "reset":
      default: {
        // do nothing
        break;
      }
    }

    return result;
  }

  [`_htmlify_{${NS_HTML}}input#text_defaultValues`] = {
    'color': '#000000',
    'range': '50',
  };

  [`_htmlify_{${NS_HTML}}input#text`](elem, {mode = "save"} = {}) {
    this[`_unhtmlify_{${NS_HTML}}input#text`](elem, {apply: false});

    let result = false;
    const elemOrig = this.getOrigNode ? this.getOrigNode(elem) : elem;
    if (!elemOrig) { return result; }

    const defaultValue = this[`_htmlify_{${NS_HTML}}input#text_defaultValues`][elem.type?.toLowerCase()] ?? '';

    switch (mode) {
      case "save-all":
      case "save": {
        const value = elemOrig.value;
        if (value !== (elem.getAttribute('value') ?? defaultValue)) {
          this.captureRewriteAttr(elem, "data-scrapbook-input-value", value, {record: false});
          result = true;
        }
        break;
      }
      case "keep-all":
      case "keep":
      case "html-all":
      case "html": {
        const value = elemOrig.value;
        if (value !== (elem.getAttribute('value') ?? defaultValue)) {
          this.captureRewriteAttr(elem, "value", value);
        }
        break;
      }
      case "reset":
      default: {
        // do nothing
        break;
      }
    }

    return result;
  }

  [`_htmlify_{${NS_HTML}}textarea`](elem, {mode = "save"} = {}) {
    this[`_unhtmlify_{${NS_HTML}}textarea`](elem, {apply: false});

    let result = false;
    const elemOrig = this.getOrigNode ? this.getOrigNode(elem) : elem;
    if (!elemOrig) { return result; }

    switch (mode) {
      case "save-all":
      case "save": {
        const value = elemOrig.value;
        if (value !== elem.textContent) {
          this.captureRewriteAttr(elem, "data-scrapbook-textarea-value", value, {record: false});
          result = true;
        }
        break;
      }
      case "keep-all":
      case "keep":
      case "html-all":
      case "html": {
        this.captureRewriteTextContent(elem, elemOrig.value);
        break;
      }
      case "reset":
      default: {
        // do nothing
        break;
      }
    }

    return result;
  }

  [`_htmlify_{${NS_HTML}}option`](elem, {mode = "save"} = {}) {
    this[`_unhtmlify_{${NS_HTML}}option`](elem, {apply: false});

    let result = false;
    const elemOrig = this.getOrigNode ? this.getOrigNode(elem) : elem;
    if (!elemOrig) { return result; }

    switch (mode) {
      case "save-all":
      case "save": {
        const selected = elemOrig.selected;
        if (selected !== elem.hasAttribute('selected')) {
          this.captureRewriteAttr(elem, "data-scrapbook-option-selected", String(selected), {record: false});
          result = true;
        }
        break;
      }
      case "keep-all":
      case "keep":
      case "html-all":
      case "html": {
        this.captureRewriteAttr(elem, "selected", elemOrig.selected);
        break;
      }
      case "reset":
      default: {
        // do nothing
        break;
      }
    }

    return result;
  }

  /**
   * Reverse htmlify recursively.
   *
   * @param {Element|Document|ShadowRoot} node
   * @param {Object} [options]
   * @param {boolean} [options.apply] - true to apply the recorded value to
   *   the element; otherwise remove the record only.
   * @param {boolean} [options.canvas] - true to handle canvas.
   * @param {boolean} [options.form] - true to handle form elements.
   * @param {boolean} [options.shadowDom] - true to handle shadowDom.
   * @param {Map} [options.adoptedStyleSheetMap] - shared map for constructed
   *   stylesheets.
   *
   * @TODO: use shared constructed stylesheets among shadow roots
   */
  unhtmlify(node, options = {}) {
    this._unhtmlify_tree(node, options);
  }

  _unhtmlify_tree(node, options = {}) {
    const {apply = true, shadowDom = true} = options;

    if (shadowDom && (node.host || node.nodeType === Node.DOCUMENT_NODE)) {
      const {adoptedStyleSheetMap = new Map()} = options;
      if (!options.adoptedStyleSheetMap) {
        const elem = node.host ?? node.documentElement;
        this._unhtmlify_sharedAdoptedStyleSheets(elem, {apply, adoptedStyleSheetMap});
      }
      this._unhtmlify_adoptedStyleSheets(node, {apply, adoptedStyleSheetMap});
    }

    if (shadowDom && node.host && node.slotAssignment === 'manual') {
      this._unhtmlify_slots(node, {apply});
    }

    this._unhtmlify(node, options);
    for (const elem of node.querySelectorAll('*')) {
      this._unhtmlify(elem, options);
    }
  }

  _unhtmlify(elem, options = {}) {
    if (elem.nodeType !== Node.ELEMENT_NODE) { return; }

    this[`_unhtmlify_{${elem.namespaceURI}}${elem.localName}`]?.(elem, options);

    this._unhtmlify_shadowHost(elem, (shadowRoot) => {
      this._unhtmlify_tree(shadowRoot, options);
    }, options);
  }

  /**
   * Recover serialized shadow DOMs and recurse into deeper shadow roots.
   *
   * @param {Element} elem - The shadow host element.
   * @param {Function} [callback] - The callback to rewrite deeper shadow roots.
   */
  _unhtmlify_shadowHost(elem, callback, {apply = true, shadowDom = true} = {}) {
    let shadowRoot = utils.getShadowRoot(elem);
    if (shadowDom) {
      const html = elem.getAttribute('data-scrapbook-shadowdom');
      if (html !== null && apply && !shadowRoot) {
        try {
          let m;
          shadowRoot = elem.attachShadow({
            mode: (m = elem.getAttribute('data-scrapbook-shadowdom-mode')) !== null ? m : 'open',
            clonable: elem.hasAttribute('data-scrapbook-shadowdom-clonable'),
            delegatesFocus: elem.hasAttribute('data-scrapbook-shadowdom-delegates-focus'),
            serializable: elem.hasAttribute('data-scrapbook-shadowdom-serializable'),
            ...((m = elem.getAttribute('data-scrapbook-shadowdom-slot-assignment')) !== null && {slotAssignment: m}),
          });
          shadowRoot.innerHTML = html;
        } catch (ex) {
          console.error(ex);
        }
      }
      this._unhtmlify_shadowHost_attrs(elem);
    }
    if (shadowRoot) {
      callback?.call(this, shadowRoot);
    }
  }

  _unhtmlify_shadowHost_attrs(elem) {
    this.captureRewriteAttr(elem, 'data-scrapbook-shadowdom', null, {record: false});
    this.captureRewriteAttr(elem, 'data-scrapbook-shadowdom-mode', null, {record: false});
    this.captureRewriteAttr(elem, 'data-scrapbook-shadowdom-clonable', null, {record: false});
    this.captureRewriteAttr(elem, 'data-scrapbook-shadowdom-delegates-focus', null, {record: false});
    this.captureRewriteAttr(elem, 'data-scrapbook-shadowdom-serializable', null, {record: false});
    this.captureRewriteAttr(elem, 'data-scrapbook-shadowdom-slot-assignment', null, {record: false});
  }

  /**
   * Recover constructed stylesheets.
   *
   * @param {Document|ShadowRoot} rootNode
   * @param {Object} [options]
   * @param {Map} [options.adoptedStyleSheetMap]
   */
  _unhtmlify_adoptedStyleSheets(rootNode, {apply = true, adoptedStyleSheetMap} = {}) {
    const elem = rootNode.host ?? rootNode.documentElement;
    const cssIndexes = elem.getAttribute('data-scrapbook-adoptedstylesheets');
    if (cssIndexes !== null) {
      if (apply && rootNode.adoptedStyleSheets) {
        const newCss = [];
        for (const idx of cssIndexes.split(',')) {
          const css = adoptedStyleSheetMap?.get(parseInt(idx, 10));
          if (!css) {
            console.error(new Error(`Missing constructed stylesheet idx: ${idx}`));
            continue;
          }
          newCss.push(css);
        }
        // Chromium < 99: adoptedStyleSheets is immutable
        rootNode.adoptedStyleSheets = newCss;
      }
      this.captureRewriteAttr(elem, 'data-scrapbook-adoptedstylesheets', null, {record: false});
    }
  }

  /**
   * Collect shared constructed stylesheets and recover special attributes.
   *
   * @param {Element} elem - The documentElement or shadow host to collect.
   * @param {Object} [options]
   * @param {Map} [options.adoptedStyleSheetMap]
   */
  _unhtmlify_sharedAdoptedStyleSheets(elem, {apply = true, adoptedStyleSheetMap} = {}) {
    const regex = /^data-scrapbook-adoptedstylesheet-(\d+)$/;
    const win = elem.ownerDocument.defaultView;
    let m;
    for (const {nodeName: attr, nodeValue: value} of Array.from(elem.attributes)) {
      if (m = regex.exec(attr)) {
        if (apply && win && adoptedStyleSheetMap) {
          const css = new win.CSSStyleSheet();
          const cssTexts = value.split('\n\n');
          for (let i = cssTexts.length - 1; i >= 0; i--) {
            try {
              cssTexts[i] && css.insertRule(cssTexts[i]);
            } catch (ex) {
              console.error(ex);
            }
          }
          adoptedStyleSheetMap.set(parseInt(m[1], 10), css);
        }
        this.captureRewriteAttr(elem, attr, null, {record: false});
      }
    }
  }

  /**
   * Recover manual assigned slots for a shadow root.
   *
   * @param {ShadowRoot} rootNode
   */
  _unhtmlify_slots(rootNode, {apply = true} = {}) {
    const COMMENT_START = /^scrapbook-slot-index=(\d+)$/;
    const COMMENT_END = '/scrapbook-slot-index';

    const host = rootNode.host;
    const slotSources = [];
    const children = host.childNodes;
    for (let i = children.length - 1; i >= 0; i--) {
      const node = children[i];
      switch (node.nodeType) {
        case Node.ELEMENT_NODE: {
          const slotIdx = node.getAttribute("data-scrapbook-slot-index");
          if (slotIdx !== null) {
            slotSources[parseInt(slotIdx, 10)] = node;
            this.captureRewriteAttr(node, "data-scrapbook-slot-index", null, {record: false});
          }
          break;
        }
        case Node.COMMENT_NODE: {
          const value = node.nodeValue;
          const m = value.match(COMMENT_START);
          if (m) {
            const next = node.nextSibling;
            if (next.nodeType === Node.TEXT_NODE) {
              slotSources[parseInt(m[1], 10)] = next;
            }
            node.remove();
            break;
          } else if (value === COMMENT_END) {
            node.remove();
            break;
          }
          break;
        }
      }
    }

    for (const elem of rootNode.querySelectorAll("slot")) {
      if (elem.namespaceURI !== NS_HTML) { continue; }
      const slotIdxes = elem.getAttribute("data-scrapbook-slot-assigned");
      if (slotIdxes === null) { continue; }
      if (apply) {
        const srcs = slotIdxes.split(',').map(i => slotSources[parseInt(i, 10)]);
        try {
          elem.assign.apply(elem, srcs);
        } catch (ex) {
          if (ex.message.includes('must have a callable @@iterator')) {
            elem.assign(srcs);
          } else {
            console.error(ex);
          }
        }
      }
      this.captureRewriteAttr(elem, "data-scrapbook-slot-assigned", null, {record: false});
    }
  }

  [`_unhtmlify_{${NS_HTML}}canvas`](elem, {apply = true, canvas = true} = {}) {
    if (!canvas) { return; }
    const canvasData = elem.getAttribute('data-scrapbook-canvas');
    if (canvasData !== null) {
      if (apply) {
        const img = new Image();
        img.onload = () => { elem.getContext('2d').drawImage(img, 0, 0); };
        img.src = canvasData;
      }
      this.captureRewriteAttr(elem, 'data-scrapbook-canvas', null, {record: false});
    }
  }

  [`_unhtmlify_{${NS_HTML}}input`](elem, {apply = true, form = true} = {}) {
    if (!form) { return; }

    switch (elem.type?.toLowerCase()) {
      case undefined:
      case "image":
      case "file": {
        return;
      }
      case "radio":
      case "checkbox": {
        return this[`_unhtmlify_{${NS_HTML}}input#radio`](elem, {apply});
      }
      default: {
        return this[`_unhtmlify_{${NS_HTML}}input#text`](elem, {apply});
      }
    }
  }

  [`_unhtmlify_{${NS_HTML}}input#radio`](elem, {apply = true} = {}) {
    const checked = elem.getAttribute('data-scrapbook-input-checked');
    if (checked !== null) {
      if (apply) {
        elem.checked = checked === 'true';
      }
      this.captureRewriteAttr(elem, 'data-scrapbook-input-checked', null, {record: false});
    }
    if (elem.type.toLowerCase() === 'checkbox') {
      const indeterminate = elem.getAttribute('data-scrapbook-input-indeterminate');
      if (indeterminate !== null) {
        if (apply) {
          elem.indeterminate = true;
        }
        this.captureRewriteAttr(elem, 'data-scrapbook-input-indeterminate', null, {record: false});
      }
    }
  }

  [`_unhtmlify_{${NS_HTML}}input#text`](elem, {apply = true} = {}) {
    const value = elem.getAttribute('data-scrapbook-input-value');
    if (value !== null) {
      if (apply) {
        elem.value = value;
      }
      this.captureRewriteAttr(elem, 'data-scrapbook-input-value', null, {record: false});
    }
  }

  [`_unhtmlify_{${NS_HTML}}textarea`](elem, {apply = true} = {}) {
    const value = elem.getAttribute('data-scrapbook-textarea-value');
    if (value !== null) {
      if (apply) {
        elem.value = value;
      }
      this.captureRewriteAttr(elem, 'data-scrapbook-textarea-value', null, {record: false});
    }
  }

  [`_unhtmlify_{${NS_HTML}}option`](elem, {apply = true} = {}) {
    const selected = elem.getAttribute('data-scrapbook-option-selected');
    if (selected !== null) {
      if (apply) {
        elem.selected = selected === 'true';
      }
      this.captureRewriteAttr(elem, 'data-scrapbook-option-selected', null, {record: false});
    }
  }
}

export {
  BaseDocumentRewriter,
  DocumentRewriter,
  MapperMixin,
};
