name: Run Tests

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency
  # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint and quick tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Verify no code issue
        run: npm run lint

      - name: Quick tests
        run: npm run test

  test:
    name: Test ${{ matrix.browser }} ${{ matrix.version }}${{ format(matrix.build && ' ({0})' || '', matrix.build) }}${{ matrix.incognito && ' (incognito)' || '' }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: lint
    continue-on-error: ${{ matrix.allow_failure || false }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Chromium MV3
          - os: windows-latest
            browser: chromium
            version: 'latest'

          # -- min major version of Chrome for Testing
          - os: windows-latest
            browser: chromium
            version: '113.0.5672.63'

          # -- min version for MV3
          # In prior versions, the background service worker becomes inactive
          # in 5 minutes, and IPC messages halt forever without waking it.
          - os: windows-latest
            browser: chromium
            version: '105.0.5114.0'

          # Chromium MV2
          # -- max major version with CLI argument to allow MV2 extension
          - os: windows-latest
            browser: chromium
            version: '149.0.7827.155'
            build: chromium2

          # -- min major version of Chrome for Testing
          - os: windows-latest
            browser: chromium
            version: '113.0.5672.63'
            build: chromium2

          - os: windows-latest
            browser: chromium
            version: '102.0.4983.1'
            build: chromium2
          - os: windows-latest
            browser: chromium
            version: '87.0.4241.0'
            build: chromium2

          # Firefox MV2
          - os: windows-latest
            browser: firefox
            version: 'latest'
          - os: windows-latest
            browser: firefox
            version: 'latest'
            incognito: true
          - os: windows-latest
            browser: firefox
            version: '109.0.1'
          - os: windows-latest
            browser: firefox
            version: '92.0.1'
          - os: windows-latest
            browser: firefox
            version: '79.0'

          # Firefox MV3
          - os: windows-latest
            browser: firefox
            version: 'latest'
            build: firefox3
          - os: windows-latest
            browser: firefox
            version: 'latest'
            build: firefox3
            incognito: true
          - os: windows-latest
            browser: firefox
            version: '109.0'
            build: firefox3

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      # Some older browsers (e.g., Firefox < 92) rely on OS mapping to
      # determine the MIME type of local (and extension internal) files.
      - name: Register .mjs MIME type
        if: ${{ matrix.os == 'windows-latest' }}
        shell: pwsh
        run: |
          New-Item -Path "HKCU:\Software\Classes\.mjs" -Force | Out-Null
          Set-ItemProperty `
            -Path "HKCU:\Software\Classes\.mjs" `
            -Name "Content Type" `
            -Value "text/javascript"

      - name: Set up browser
        shell: pwsh
        run: |
          $browser = "${{ matrix.browser }}"
          $version = "${{ matrix.version }}"

          $targetDir = "$env:USERPROFILE/browsers"
          New-Item -ItemType Directory -Force -Path $targetDir | Out-Null

          if ($browser -eq "chromium") {
            if ($version -eq "latest") {
              echo "Searching for the latest version of Chrome for Testing ..."
              $data = Invoke-RestMethod `
                  -Uri "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json"
              $stable = $data.channels.Stable
              $version = $stable.version
              $appSrc = $stable.downloads.chrome |
                  Where-Object platform -eq "win64" |
                  Select-Object -ExpandProperty url
              $appSubpath = "chrome-win64/chrome.exe"
              $driverSrc = $stable.downloads.chromedriver |
                  Where-Object platform -eq "win64" |
                  Select-Object -ExpandProperty url
              $driverSubpath = "chromedriver-win64"
              echo "version: $version"
              echo "appSrc: $appSrc"
              echo "appSubpath: $appSubpath"
              echo "driverSrc: $driverSrc"
              echo "driverSubpath: $driverSubpath"
            }
            elseif ([version]$version -ge [version]"113.0") {
              # Use Chrome for Testing when available
              # https://googlechromelabs.github.io/chrome-for-testing/
              $data = Invoke-RestMethod `
                  -Uri "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json"
              $item = $data.versions | Where-Object { $_.version -eq $version }
              $appSrc = $item.downloads.chrome |
                  Where-Object platform -eq "win64" |
                  Select-Object -ExpandProperty url
              $appSubpath = "chrome-win64/chrome.exe"
              $driverSrc = if ($null -ne $item.downloads.chromedriver) {
                $item.downloads.chromedriver |
                    Where-Object platform -eq "win64" |
                    Select-Object -ExpandProperty url
              } else {
                ""
              }
              $driverSubpath = "chromedriver-win64"
              echo "appSrc: $appSrc"
              echo "appSubpath: $appSubpath"
              echo "driverSrc: $driverSrc"
              echo "driverSubpath: $driverSubpath"
            }
            else {
              # Use portable Chromium
              # https://www.chromium.org/getting-involved/download-chromium/
              $data = Invoke-RestMethod `
                  -Uri "https://github.com/vikyd/chromium-history-version-position/raw/refs/heads/master/json/ver-pos-os/version-position-Win_x64.json"
              $position = $data.$version
              # $appDir = "https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/${position}/"
              $appSrc = "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F${position}%2Fchrome-win.zip?alt=media"
              $appSubpath = "chrome-win/chrome.exe"
              $driverSrc = "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F${position}%2Fchromedriver_win32.zip?alt=media"
              $driverSubpath = "chromedriver_win32"
              echo "appSrc: $appSrc"
              echo "appSubpath: $appSubpath"
              echo "driverSrc: $driverSrc"
              echo "driverSubpath: $driverSubpath"
            }

            $appZip = "$targetDir/chrome.zip"
            $appDir = "$targetDir/chrome"
            Invoke-WebRequest -Uri $appSrc -OutFile $appZip
            Expand-Archive -Path $appZip -DestinationPath $appDir -Force
            echo "EXE_PATH=$appDir/$appSubpath" >> $env:GITHUB_ENV

            if ($driverSrc) {
              $driverZip = "$targetDir/chromedriver.zip"
              $driverDir = "$targetDir/chromedriver"
              Invoke-WebRequest -Uri $driverSrc -OutFile $driverZip
              Expand-Archive -Path $driverZip -DestinationPath $driverDir -Force
              Add-Content -Path $env:GITHUB_PATH -Value "$driverDir/$driverSubpath"
            } else {
              # Skip the preinstalled browser drivers in PATH and let selenium determine
              # according to the passed executable.
              echo "SE_SKIP_DRIVER_IN_PATH=true" >> $env:GITHUB_ENV
            }
          }
          elseif ($browser -eq "firefox") {
            if ($version -ne "latest") {
              $appSrc = "https://ftp.mozilla.org/pub/firefox/releases/$version/win64/en-US/Firefox%20Setup%20$version.exe"
              $appSubpath = "core/firefox.exe"
              echo "appSrc: $appSrc"
              echo "appSubpath: $appSubpath"

              $appFile = "$targetDir/firefox-setup.exe"
              $appDir = "$targetDir/firefox"
              Invoke-WebRequest -Uri $appSrc -OutFile $appFile
              7z x $appFile -o"$appDir" -y | Out-Null
              echo "EXE_PATH=$appDir/$appSubpath" >> $env:GITHUB_ENV
            }

            # Skip the preinstalled browser drivers in PATH and let selenium determine
            # according to the passed executable.
            echo "SE_SKIP_DRIVER_IN_PATH=true" >> $env:GITHUB_ENV
          }

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - name: Install backend
        run: pip install webscrapbook

      - name: Run tests
        shell: pwsh
        run: |
          $browser = "${{ matrix.browser }}"
          $version = "${{ matrix.version }}"
          echo "browser: $browser"
          echo "version: $version"

          $build = "${{ matrix.build }}"
          if (-not $build) {
            $build = if (
              ($browser -eq "chromium") -and
              ($version -ne "latest") -and
              ([version]$version -lt [version]"102.0")
            ) {
              "chromium2"
            } else {
              $browser
            }
          }
          echo "build: $build"

          $incognito = "${{ matrix.incognito }}"
          echo "incognito: $incognito"

          $argsList = @()
          $argsList += "--verbose"

          $argsList += "--browser"
          $argsList += $browser

          if ($env:EXE_PATH) {
            $argsList += "--exe-path"
            $argsList += $env:EXE_PATH
          }

          if ($incognito) {
            $argsList += "--incognito"
          }

          $process = Start-Process "python" `
              -ArgumentList (Join-Path $env:GITHUB_WORKSPACE "test" "server.py") `
              -RedirectStandardOutput (Join-Path $env:TEMP "server-stdout.log") `
              -RedirectStandardError (Join-Path $env:TEMP "server-stderr.log") `
              -PassThru
          echo "Started servers with PID: $($process.Id)"

          npm run "dev:$build"
          node test/browser-runner.js $argsList

          Stop-Process -Id $process.Id
