name: Run Tests

on:
  push:
  pull_request:

concurrency:
  # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency
  # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Verify no code issue
        run: npm run lint

      - name: Quick tests
        run: npm run test
